#******************************************************************************
#* INF 610 - Estruturas de Dados e Algoritmos - 2018/2                        *
#*                                                                            *
#* Lista de exercícios 3                                                      *
#*                                                                            *
#* Marcelo de Matos Menezes - 75254                                           *
#*                                                                            *
#*****************************************************************************/


debug:
	g++ debug.cpp -o debug -std=c++11 -DODA_DEBUG -DRBT_DEBUG

benchmark:
	g++ benchmark.cpp -o benchmark -std=c++11 -O3 -DWRITE_TO_FILE